name: "Close Stale Issues"

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Close stale issues
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          days-before-stale: 60  # 60天无活动则标记为stale
          days-before-close: 7   # 标记为stale后7天关闭
          stale-issue-label: 'stale'  # 标记stale的Label
