name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    # This runs every day 20 minutes before midnight: https://crontab.guru/#40_23_*_*_*
    - cron: '0 9 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        id: stale-no-repro
        name: 'Close stale issues with no reproduction'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          any-of-labels: 'waiting for customer response'
          close-issue-message: 'This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.'
          days-before-issue-close: 1
          days-before-issue-stale: 7
          days-before-pr-close: -1
          days-before-pr-stale: -1
          exempt-issue-labels: 'blocked,must,should,keep'
          operations-per-run: 300 # 1 operation per 100 issues, the rest is to label/comment/close
